name: gait3
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.1.0
  - aom=3.12.1
  - blas=1.0
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - contourpy=1.3.3
  - cycler=0.12.1
  - dav1d=1.2.1
  - expat=2.7.3
  - filelock=3.20.0
  - fontconfig=2.15.0
  - fonttools=4.61.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - gettext=0.21.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.2
  - graphite2=1.3.14
  - grpcio=1.74.1
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.11
  - jinja2=3.1.6
  - jpeg=9f
  - kiwisolver=1.4.9
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250814.1
  - libavif=1.3.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgfortran5=15.2.0
  - libglib=2.84.4
  - libgrpc=1.74.1
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libprotobuf=6.33.0
  - libre2-11=2025.11.05
  - libtiff=4.7.1
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown=3.8
  - markupsafe=3.0.2
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.6.1
  - numpy=2.3.5
  - numpy-base=2.3.5
  - openssl=3.6.0
  - packaging=25.0
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - protobuf=6.33.0
  - pycparser=2.23
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - pytorch=2.5.1
  - pyyaml=6.0.3
  - re2=2025.11.05
  - readline=8.3
  - requests=2.32.5
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.0
  - sympy=1.14.0
  - tensorboard=2.20.0
  - tensorboard-data-server=0.7.0
  - tk=8.6.15
  - torchvision=0.20.1
  - tornado=6.5.4
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.1
  - werkzeug=3.1.3
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - pygame==2.6.1
prefix: /Users/nanh/anaconda3/envs/gait3
